name: Ubuntu RDP (Xfce) via Remote.it Agent Install

on: workflow_dispatch

jobs:
  ubuntu-rdp:
    if: github.repository == 'Hasnain1385/Linux'  # Prevents fork abuse
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Setup desktop environment
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies xrdp curl openssh-client

      - name: Configure xrdp and user
        run: |
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          sudo adduser --disabled-password --gecos "" githubuser
          echo "githubuser:rdppassword" | sudo chpasswd
          sudo usermod -aG sudo githubuser

      - name: Mask Remote.it Registration Code
        env:
          REMOTEIT_REGISTRATION_CODE: ${{ secrets.REMOTEIT_REGISTRATION_CODE }}
        run: |
          echo "::add-mask::$REMOTEIT_REGISTRATION_CODE"

      - name: Install and Register Remote.it Agent
        env:
          R3_REGISTRATION_CODE: ${{ secrets.REMOTEIT_REGISTRATION_CODE }}
        run: |
          curl -L https://downloads.remote.it/remoteit/install_agent.sh | sh

      - name: Show RDP login info
        run: |
          echo "=============================="
          echo "RDP Username: githubuser"
          echo "RDP Password: rdppassword"
          echo "Find the device at: https://app.remote.it"
          echo "(Service will be named 'RDP' or similar)"
          echo "=============================="

      - name: Keep runner alive
        run: sleep 1800  # 30 minutes
