name: Ubuntu RDP (Xfce) via Remote.it

on: workflow_dispatch

jobs:
  ubuntu-rdp:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - name: Setup desktop environment
        run: |
          sudo apt update
          sudo apt install -y xfce4 xfce4-goodies xrdp curl openssh-client

      - name: Configure xrdp and user
        run: |
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          sudo adduser --disabled-password --gecos "" githubuser
          echo "githubuser:rdppassword" | sudo chpasswd
          sudo usermod -aG sudo githubuser

      - name: Install Remote.it CLI
        run: |
          curl -L https://downloads.remote.it/cli/remoteit-linux-arm64.tar.gz -o remoteit.tar.gz
          tar -xzf remoteit.tar.gz
          sudo install remoteit /usr/local/bin/

      - name: Authenticate and register RDP service
        env:
          REMOTEIT_ACCESS_KEY_ID: ${{ secrets.REMOTEIT_ACCESS_KEY_ID }}
          REMOTEIT_ACCESS_KEY_SECRET: ${{ secrets.REMOTEIT_ACCESS_KEY_SECRET }}
        run: |
          remoteit auth --id "$REMOTEIT_ACCESS_KEY_ID" --key "$REMOTEIT_ACCESS_KEY_SECRET"
          remoteit connectd install
          remoteit add --name "Github-RDP" --port 3389 --host 127.0.0.1 --type rdp
          remoteit start

      - name: Display RDP login info
        run: |
          echo "==========================="
          echo "RDP Login: githubuser"
          echo "RDP Password: rdppassword"
          echo "Remote.it Device/Service: Github-RDP"
          echo "Access it at: https://app.remote.it"
          echo "==========================="

      - name: Keep runner alive
        run: sleep 1800  # 30 minutes
